### ISSUE TITLE
No libvstdlib_srv.so file.

### ISSUE THREAD

**Issue by roxcity** [ErikMinekus/sm-ripext#1]
[SM] Unable to load extension "rip.ext": libvstdlib_srv.so: cannot open shared object file: No such file or directory.

I couldn't find libvstdlib_srv.so but I found libvstdlib_s.so.

**Comment by CrazyHackGUT** [comment]
I'm seeing the same problem. CS:GO, Linux.
At the same time, on Windows this problem is not observed.
![image](http://i.imgur.com/iCa5iIH.png)

**Comment by ErikMinekus** [comment]
Correct, that library was only renamed on CS:GO Linux. I'm currently only compiling against the Source 2013 SDK, so I'll have to check if there's a proper way to create one file for all games, or if I have to go back to one file per SDK.
