### ISSUE TITLE
Finding if a key exists within a response.

### ISSUE THREAD

**Issue by GabeHirakawa** [ErikMinekus/sm-ripext#11]
I'm having an issue finding if a key exists without the plugin erroring out and not proceeding to the rest of the plugin.

Essentially what I'm trying to do is find out if my API responds with an {"error":"Incorrect credentials"} or some other error message. I want to see if that key exists. I tried turning the JSONObject to a string and just doing a StrContains() on it, but that in my mind doesn't seem like the cleanest nor the best way to do it, and it didn't seem to work either. 

What I'm trying to essentially accomplish is the following:

```
public SomeResponseCallback (HTTPResponse response, any data)
{
    JSONObject info = view_as<JSONObject>(response.Data);
    if (info.Contains("error"))
    {
        //report error
    }
    //if no error found continue
}
```
What would the best way of going about this be? I wasn't able to see a viable function for this, but maybe I'm overlooking the obvious.

**Comment by GabeHirakawa** [comment]
Wow, after posting this I decided to look at the .inc files one more time to make sure. Maybe I should have done that before posting because I just found the following function. Sorry about that.

`Public native bool IsNull(const char[] key);`

**Comment by ErikMinekus** [comment]
Usually you would return a different HTTP status code when an error occurs, and check for that.

```
public SomeResponseCallback (HTTPResponse response, any data)
{
    JSONObject info = view_as<JSONObject>(response.Data);
    if (response.Status != HTTPStatus_OK)
    {
        char error[256];
        info.GetString("error", error, sizeof(error));
        //report error
    }
    //if no error found continue
}
```

**Comment by GabeHirakawa** [comment]
I should probably stop looking at code when I'm half asleep, looks like a I grossly misunderstood what IsNull was supposed to do. 

Also, in regards to your response, what if in the event there isn't an error and in fact a key isn't delivered because it doesn't apply to that specific client?

In the API I'm using a users "subscription" info is delivered only _if_ the specific user is in fact a subscriber. And in that scenario returning a HTTP status code other than 200 OK isn't needed because the request for information was successful.

**Comment by ErikMinekus** [comment]
If "subscription" is a relation of "user", it should be set to null if there is no data for that relation. Just like a LEFT JOIN in SQL.
