### ISSUE TITLE
[Feature request] Custom SSL certificate validation

### ISSUE THREAD

**Issue by muukis** [ErikMinekus/sm-ripext#12]
I'd like the HTTPClient to have a way for creating custom SSL certificate validation. Similar to this .NET related issue: [StackOverflow link](https://stackoverflow.com/questions/526711/using-a-self-signed-certificate-with-nets-httpwebrequest-response)

This code example (all certificates allowed):
`HTTPClient.ServerCertificateValidationCallback = delegate { return true; };`

I will check the code if I can do it myself...

**Comment by ErikMinekus** [comment]
If you want to validate your own SSL certificates, you can already place a custom CA bundle in ```addons/sourcemod/configs/ripext```.

**Comment by muukis** [comment]
Ok, that'll do for me - thanks.
I am not sure how is it supposed to be done (place a custom CA bundle in `addons/sourcemod/configs/ripext`, so I added my certificate export in the file ca-bundle.crt, and now it works. I tried adding some custom named file with the certificate as content to the folder you've mentioned, but that didn't work.
