### ISSUE TITLE
Potential memory leak

### ISSUE THREAD

**Issue by CrazyHackGUT** [ErikMinekus/sm-ripext#14]
https://github.com/ErikMinekus/sm-ripext/blob/55e1f0126490e06577677a89cfee433e07e14943/httpthread.cpp#L42-L46

If OS doesn't reallocate memory, she also doesn't remove data by old pointer.
But we rewrite pointer, and if OS doesn't reallocated memory - we also lose some memory.

**Comment by ErikMinekus** [comment]
This code is taken straight from https://curl.haxx.se/libcurl/c/getinmemory.html, so if you believe there's a possible memory leak when ```realloc()``` returns NULL, I suggest creating an issue on https://github.com/curl/curl so they can fix their example.

**Comment by CrazyHackGUT** [comment]
I created issue. 
One from developers confirmed problem. 

https://github.com/curl/curl/issues/2991

**Comment by CrazyHackGUT** [comment]
https://github.com/curl/curl/commit/23524bf85b887adbc513bc015c9530355967bc04
