### ISSUE TITLE
POST don't send any params

### ISSUE THREAD

**Issue by Matix8981** [ErikMinekus/sm-ripext#17]
I created simple debugging script in PHP for check if rest in pawn sending POST data to target HTTP but can't see any POST data in apache logs i see request from my csgo server.
https://pastebin.com/0e2ecBdk
Output JSON file:
`[[],[],[]]`
Plugin:
https://pastebin.com/5zbUtY8U

**Comment by indietyp** [comment]
excerpt from www.php.net/manual/en/reserved.variables.post.php

```
An associative array of variables passed to the current script via the HTTP POST method when using application/x-www-form-urlencoded or multipart/form-data as the HTTP Content-Type in the request.
```

as you can see the sent data is json and not x-www-form-urlencoded therefore $_POST is empty.

**Comment by Matix8981** [comment]
```
header("Content-Type: application/x-www-form-urlencoded");
```
Dont give result

**Comment by ErikMinekus** [comment]
To get the request body in PHP:
```php
$content = file_get_contents('php://input');
```

**Comment by indietyp** [comment]
setting the header does not implicitly change the format of the request body.

an example:
A JSON payload looks like this:
```json
{
	"a": "b"
}
```

while an application/x-www-form-urlencoded looks like this:
```url
a=b
```

as you can see those are inherently different - changing the header won't change the actual body content and formatting.

**Comment by Matix8981** [comment]
> 
> 
> To get the request body in PHP:
> 
> ```
> $body = file_get_contents('php://input');
> ```
> 
> Then use [json_decode](https://php.net/json_decode) to parse it as JSON.

This resolve is good and works :) Thanks

**Comment by udee297** [comment]
hi,
i got same issue,
on my web server i already use this
$jsonString = file_get_contents("php://input");
  $myFile = "player-".date('his', time()).".json";
  file_put_contents($myFile,$jsonString);

and plugin using this
HTTPClient httpClient;
httpClient = new HTTPClient(APIURL);
JSONObject player = new JSONObject();
player.SetString("id", authid);
player.SetString("ip", ip_address);
httpClient.Post("api.php", player, OnPlayerLoad, client);
delete player;

but i still got blank on my web server..

but if i use curl on my gameserver, its working fine 
curl -d '{"id":"327mm1327821378","ip":"123.123.123.11"}' http://website.com/api.php
i can see json file on my web

**Comment by udee297** [comment]
@ErikMinekus its correct right?
