### ISSUE TITLE
Extension not making requests on windows?

### ISSUE THREAD

**Issue by robertnisipeanu** [ErikMinekus/sm-ripext#23]
I cloned the project, added a function to test some things related to issue #22 and after I compiled the extension and put it on the local dev server I realized that the requests where never done. I thought it's maybe something on my part or my compiler, however downloaded the latest released version and same thing.
I've modified the test script to print some logs, and it seems no error is giving while executing methods like .Get, .Post as the log after them gets printed. Also checked on my local access.log, and there is no request that has been made.
Here is the test file used: https://pastebin.com/Xn3vBG8z
And this is my console:

```
sm plugins unload_all
[SM] All plugins have been unloaded.
sm plugins refresh
CGameEventManager::AddListener: event 'teamplay_win_panel' unknown.
CGameEventManager::AddListener: event 'teamplay_restart_round' unknown.
CGameEventManager::AddListener: event 'arena_win_panel' unknown.
LOADED PLUGIN RIPEXT
Initialized all requests
[SM] The plugin list has been refreshed and reloaded.
sm
SourceMod Menu:
Usage: sm <command> [arguments]
    cmds             - List console commands
    config           - Set core configuration options
    credits          - Display credits listing
    cvars            - View convars created by a plugin
    exts             - Manage extensions
    plugins          - Manage Plugins
    prof             - Profiling
    version          - Display version information
sm version
 SourceMod Version Information:
    SourceMod Version: 1.10.0.6488
    SourcePawn Engine: 1.10.0.6488, jit-x86 (build 1.10.0.6488)
    SourcePawn API: v1 = 5, v2 = 12
    Compiled on: Apr 30 2020 16:35:23
    Built from: https://github.com/alliedmodders/sourcemod/commit/afb40f1d
    Build ID: 6488:afb40f1d
    http://www.sourcemod.net/

```

I have not yet tested it on Linux, so I do not know if this is OS related, but that's my suspicion.

**Comment by ErikMinekus** [comment]
Are you sure the server is not hibernating?

**Comment by robertnisipeanu** [comment]
That seemed to be the case, didn't even knew that srcds goes into hibernation mode if there is no player online. I'll close the issue, thanks for the help.
