### ISSUE TITLE
POST result empty json 

### ISSUE THREAD

**Issue by udee297** [ErikMinekus/sm-ripext#25]
hi, sorry maybe its like the other issue from matix but cant get it work

on my web server i already use this
$jsonString = file_get_contents("php://input");
$myFile = "player-".date('his', time()).".json";
file_put_contents($myFile,$jsonString);

and plugin using this
HTTPClient httpClient;
httpClient = new HTTPClient(APIURL);
JSONObject player = new JSONObject();
player.SetString("id", authid);
player.SetString("ip", ip_address);
httpClient.Post("api.php", player, OnPlayerLoad, client);
delete player;

but i still got blank on my web server..

but if i use curl from my gameserver, its working fine
curl -d '{"id":"327mm1327821378","ip":"123.123.123.11"}' http://website.com/api.php
i can see json file on my web

**Comment by ErikMinekus** [comment]
Your code looks fine. Are you sure APIURL is correct? Are there any errors in the SourceMod logs?

**Comment by saintplay** [comment]
can you try connecting a player to your server and then running your request?
I think the last CSGO update break networking from hibernating servers

**Comment by udee297** [comment]
its my webhosting. i tried to host on another webhost and its working fine. i wonder whats wrong with old hosting
