### ISSUE TITLE
UploadFile not freeing file after upload completed.

### ISSUE THREAD

**Issue by iBoonie** [ErikMinekus/sm-ripext#28]
I have found that after a file has been uploaded, the file never gets freed and is locked by SRCDS. You cannot delete the file until you restart the server.

I thought HTTPClient might not have been being closed, so I tried deleting the handle after it finished the upload, but that didn't fix it. I'm not sure if this would cause crashes down the line if you upload a bunch of files or not.

**Comment by ErikMinekus** [comment]
Thanks, it looks like none of the requests were properly cleaned up in 1.2.0. Can you try https://github.com/ErikMinekus/sm-ripext/releases/tag/1.2.1 ?

**Comment by iBoonie** [comment]
That worked, thanks!
