### ISSUE TITLE
OnDownloadedCallback call before file write done

### ISSUE THREAD

**Issue by BoneTM** [ErikMinekus/sm-ripext#36]
get empty file in the callback.
file is actually downloaded, if i create a timer to get the file later would be ok.
i think this callback is after file write is correct?

**Comment by ErikMinekus** [comment]
You're right, I think the file is currently written after the callback is called, it should be written before.

**Comment by BoneTM** [comment]
> You're right, I think the file is currently written after the callback is fired, I will change it so it writes the file before firing the callback.

thanks
