### ISSUE TITLE
default connectTimeout question

### ISSUE THREAD

**Issue by wopox1337** [ErikMinekus/sm-ripext#37]
Why [default ](https://github.com/ErikMinekus/sm-ripext/blob/master/httpclient.h#L61) `connectTimeout` = 10 when libCurl describes this value as 300?
`Set to zero to switch to the default built-in connection timeout - 300 seconds.`
https://curl.se/libcurl/c/CURLOPT_CONNECTTIMEOUT.html

And also this incident is not reflected in the documentation
https://github.com/ErikMinekus/sm-ripext/blob/master/pawn/scripting/include/ripext/http.inc#L173-L177

**Comment by ErikMinekus** [comment]
Because REST in Pawn does not have a way to cancel a request once it has started, I think 10 seconds is more than reasonable to wait for the connection, especially since you can change it if needed.

I'll make sure these default values are documented.
