### ISSUE TITLE
Fails to build, no member 'chars'

### ISSUE THREAD

**Issue by Peak-CDE** [ErikMinekus/sm-ripext#42]
Failing to build httpclient.cpp at HTTPRequest::BuildHeaders [https://github.com/ErikMinekus/sm-ripext/blob/f50b9e4ffc8c74dec5cec7b9a734ad860aefffe1/httprequest.cpp#L106](https://github.com/ErikMinekus/sm-ripext/blob/f50b9e4ffc8c74dec5cec7b9a734ad860aefffe1/httprequest.cpp#L106) with error:

```
/home/peak/alliedmodders/sourcemod/extensions/sm-ripext/httpclient.cpp:48:56: error: no member named 'chars' in 'std::__cxx11::basic_string<char>'
                snprintf(header, sizeof(header), "%s: %s", iter->key.chars(), iter->value.c_str());
                                                           ~~~~~~~~~ ^
1 error generated.```

**Comment by ErikMinekus** [comment]
You need to change `chars` to `c_str`, or build against the `1.10-dev` SourceMod branch
