### ISSUE TITLE
NodeJS: float certain values as an integer

### ISSUE THREAD

**Issue by Wend4r** [ErikMinekus/sm-ripext#45]
When does response from the backend on NodeJS, Rest In Pawn cannot read this integer float values through `JSONObject.GetFloat()`.
```node
> JSON.stringify({"float": 1.0})
'{"float":1}'
```

But `JSONObject.GetFloat()` works in the case of
```node
> JSON.stringify({"float": 1.1})
'{"float":1.1}'
```
I suggest to make reading of integers even as float.

**Comment by ErikMinekus** [comment]
JavaScript does not have distinct types for integers and floats, so `JSON.stringify()` outputs `1.0` as `1`, which I can only interpret as an integer. `JSONObject.FromFile()` and `.FromString()` do support the `JSON_DECODE_INT_AS_REAL` flag, which interprets all numbers as floats, but it's currently not possible to use decoding flags with an HTTP response. I will consider that for the future.

**Comment by Wend4r** [comment]
With #52, I can control float and integer values.
