### ISSUE TITLE
Version GLIBC_2.28 not found

### ISSUE THREAD

**Issue by crashzk** [ErikMinekus/sm-ripext#50]
Latest versions of REST in Pawn I have been getting this error:
```
[11] <FAILED> file "rip.ext.so": /lib/i386-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /home/clientes/OGP_User_Files/whmcs/5138/csgo/addons/sourcemod/extensions/rip.ext.so)
```
As I understand I would have to update GLIBC to version 2.28 or higher.

Currently where I host my servers runs on Ubuntu 18.04 LTS operating system, any solution for those who use this version of Ubuntu?

Or just updating Ubuntu to 20.04 or using older versions of REST in Pawn anyway?

**Comment by ErikMinekus** [comment]
I have rereleased [version 1.3](https://github.com/ErikMinekus/sm-ripext/releases/tag/1.3.0), but built against Ubuntu 18.04 instead of 20.04, which seems to solve the issue.

Thanks for the report!
