### ISSUE TITLE
Requests are not processed during hibernation

### ISSUE THREAD

**Issue by almazoff-gh** [ErikMinekus/sm-ripext#55]
Plugin don't working on windows, he don't execute callback function!

**Comment by ErikMinekus** [comment]
Your server is probably hibernating. Make sure someone is in the server, or disable hibernation.

**Comment by almazoff-gh** [comment]
> Your server is probably hibernating. Make sure someone is in the server, or disable hibernation.

Then this is a big minus, SteamWorks for example works even in sleep mode

**Comment by CrazyHackGUT** [comment]
> SteamWorks for example works even in sleep mode

SteamWorks can't work in sleep mode because this is SourceMod platform limitations.

**Comment by ErikMinekus** [comment]
> SteamWorks for example works even in sleep mode

Do you have a plugin that proves this? Most of SourceMod's code is tied to game frames, which are not processed during hibernation (see https://github.com/alliedmodders/sourcemod/pull/540#issuecomment-258149727 and https://forums.alliedmods.net/showthread.php?p=2449435#post2449435). So how can you perform a request when SourceMod doesn't run any code?

**Comment by ErikMinekus** [comment]
As of SourceMod 1.11.6728, game frames are processed during hibernation.
