### ISSUE TITLE
BADCERT_NOT_TRUSTED

### ISSUE THREAD

**Issue by HenryTownshand** [ErikMinekus/sm-ripext#6]
How to remove this error:
[RIPEXT] HTTP request failed: Cert verify failed: BADCERT_NOT_TRUSTED

**Comment by ErikMinekus** [comment]
It sounds like the SSL certificate of the URL is not trusted. Have you tried Googling the error?

**Comment by HenryTownshand** [comment]
Google did not give anything

**Comment by ErikMinekus** [comment]
Version [1.0.3](https://github.com/ErikMinekus/sm-ripext/releases/tag/1.0.3) now puts the CA bundle in the ```configs/ripext``` folder, so if your API's SSL certificate is not trusted, you can create your own CA bundle and replace the default one.
