### ISSUE TITLE
Empty Body POST over HTTP

### ISSUE THREAD

**Issue by PhlexPlexico** [ErikMinekus/sm-ripext#71]
Hiya,

I think there may be an issue with communications over HTTP on Linux game servers. I've had a few users attempting to use a plugin that uses sm-ripext to POST some match data to an API, but the only difference from my instances (which is working) vs. theirs is that they are using HTTP and not HTTPS. Logging the request prior to, it appears that the request contains all the proper body, but upon receiving it on the API side, the body remains empty. I know there was some JSON issues with windows and HTTP/2, so I was wondering if there may be a similar issue when communicating over HTTP with any type of server?

Thanks!

**Comment by ErikMinekus** [comment]
I have not encountered this myself, but maybe it was the same issue as #68.

Can they try this build: https://github.com/ErikMinekus/sm-ripext/suites/5700970486/artifacts/187824424

**Comment by PhlexPlexico** [comment]
Will do, thanks for this and I'll report as soon as someone gets back to me (or once I test with an http server as well) :)

**Comment by Bunker56** [comment]
It`s working!!! Thanks!..

**Comment by PhlexPlexico** [comment]
Hah perfect, will close this off then. Thanks for testing and glad this was an easy/already implemented fix :)
