### ISSUE TITLE
Error "HTTP request failed"

### ISSUE THREAD

**Issue by Dreizehnt** [ErikMinekus/sm-ripext#8]
Hi, i cant use this extension on my server. Technical support for hosting where I rent the game server states that the extension visits the directories above the server folder and should not do this. How to be? And what actions are performed in the folder: **/etc/ssl/certs/**
`L 08/22/2017 - 16:34:39: [RIPEXT] HTTP request failed: Error reading ca cert file /etc/ssl/certs/ca-certificates.crt - mbedTLS: (-0x3E00) PK - Read/write of file failed`

Can u help?

**Comment by ErikMinekus** [comment]
```/etc/ssl/certs/``` is where the trusted SSL certificates are stored on Ubuntu. Unfortunately this path is different for other Linux distributions, so I will work on including the certificates with the extension.

**Comment by ErikMinekus** [comment]
Version [1.0.3](https://github.com/ErikMinekus/sm-ripext/releases/tag/1.0.3) now puts the CA bundle in the ```configs/ripext``` folder, which should fix the issue.
